### ISSUE TITLE
Feedback form restricted

### ISSUE THREAD

**Issue by luebken** [askmeegs/build-a-platform-with-krm#23]
The [form](https://docs.google.com/forms/d/e/1FAIpQLSc9epFCgadDtx9yJoWbT6_5Zf7UaRTiyptYwpd1oH9_-tg-Ew/formrestricted) linked from [this page](https://github.com/askmeegs/build-a-platform-with-krm/blob/main/5-hosted-resources/partC-existing-resources.md) is not accessible for me: 

![image](https://user-images.githubusercontent.com/53055/134471325-80c1d5da-5c31-4d93-b717-7342fa284d50.png)

**Comment by askmeegs** [comment]
Fixed!
https://docs.google.com/forms/d/e/1FAIpQLSfSiVe4fwZv_S19n7pSNoct_pO2KfQ0-Q5SPWsYr4L2GxFXXw/viewform

Hyperlink in part 5 updated as well. 

Thank you!
